ALLOWED_STATUSES = {"DRAFT", "PUBLISHED", "DELETED", "ARCHIVED"}
ALLOWED_SCORING_MODES = {"WEIGHTED", "UNWEIGHTED"}

DRAFT_STATUS = "DRAFT"
PUBLISHED_STATUS = "PUBLISHED"
DELETED_STATUS = "DELETED"
ARCHIVED_STATUS = "ARCHIVED"

WEIGHTED_MODE = "WEIGHTED"
UNWEIGHTED_MODE = "UNWEIGHTED"
