"""Initial tables migration

Revision ID: 4b67b5287c7a
Revises: 'None'
Create Date: 2026-08-24 11:16:58.528655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b67b5287c7a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('market', sa.String(length=100), nullable=False),
    sa.Column('campaign_name', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    op.create_table('metadata',
    sa.Column('metadata_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market', sa.String(length=100), nullable=False),
    sa.Column('retailer', sa.JSON(), nullable=False),
    sa.Column('channel', sa.JSON(), nullable=False),
    sa.Column('category', sa.JSON(), nullable=False),
    sa.Column('accountable_team', sa.JSON(), nullable=False),
    sa.Column('pillar_kpi_1', sa.JSON(), nullable=False),
    sa.Column('pillar_kpi_2', sa.JSON(), nullable=False),
    sa.Column('pillar_kpi_3', sa.JSON(), nullable=False),
    sa.Column('pillar_kpi_4', sa.JSON(), nullable=False),
    sa.Column('pillar_kpi_5', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('metadata_id'),
    sa.UniqueConstraint('market')
    )
    op.create_table('pager',
    sa.Column('pager_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('market', sa.String(length=100), nullable=True),
    sa.Column('retailer', sa.String(length=100), nullable=True),
    sa.Column('channel', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('campaign_focus', sa.String(length=100), nullable=True),
    sa.Column('business_outcome_statement', sa.String(length=1000), nullable=True),
    sa.Column('scoring_mode', sa.Enum('WEIGHTED', 'UNWEIGHTED', name='scoringmode', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'DELETED', 'ARCHIVED', name='pagerstatus', native_enum=False), nullable=False),
    sa.Column('track', sa.String(length=100), nullable=True),
    sa.Column('pager_type', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by', sa.String(length=100), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('pager_id')
    )
    op.create_table('pillar',
    sa.Column('pillar_id', sa.String(length=36), nullable=False),
    sa.Column('pager_id', sa.String(length=36), nullable=False),
    sa.Column('pillar_number', sa.Integer(), nullable=False),
    sa.Column('pillar_name', sa.String(length=255), nullable=True),
    sa.Column('pillar_description', sa.String(length=1000), nullable=True),
    sa.Column('pillar_weight', sa.Float(), nullable=True),
    sa.Column('pillar_track', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pager_id'], ['pager.pager_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pillar_id')
    )
    op.create_table('pillar_initiative',
    sa.Column('pillar_initiative_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('initiative_id', sa.String(length=36), nullable=False),
    sa.Column('pager_id', sa.String(length=36), nullable=False),
    sa.Column('pillar_id', sa.String(length=36), nullable=False),
    sa.Column('initiative_number', sa.Integer(), nullable=False),
    sa.Column('initiative_track', sa.String(length=100), nullable=True),
    sa.Column('priority_level', sa.String(length=20), nullable=True),
    sa.Column('accountable_function_department', sa.String(length=255), nullable=True),
    sa.Column('initiative_description', sa.String(length=2000), nullable=True),
    sa.Column('kpi_metric', sa.String(length=255), nullable=True),
    sa.Column('success_target', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('week_start', sa.String(length=20), nullable=True),
    sa.Column('week_end', sa.String(length=20), nullable=True),
    sa.Column('guidelines', sa.String(length=2000), nullable=True),
    sa.Column('checklist_compliance_notes', sa.String(length=2000), nullable=True),
    sa.Column('image_urls', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pager_id'], ['pager.pager_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pillar_id'], ['pillar.pillar_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pillar_initiative_id'),
    sa.UniqueConstraint('initiative_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pillar_initiative')
    op.drop_table('pillar')
    op.drop_table('pager')
    op.drop_table('metadata')
    op.drop_table('campaign')
    # ### end Alembic commands ###
